USE master
IF EXISTS(SELECT* FROM SYS.DATABASES WHERE NAME ='QuanlySV')
	DROP DATABASE QuanlySV
GO
CREATE DATABASE QuanlySV
GO
USE QuanlySV

IF EXISTS(SELECT * FROM SYS.objects WHERE NAME='Lop')
	DROP TABLE Lop
CREATE TABLE Lop
(
	MaLop CHAR(3) NOT NULL primary key,
	TenLop NVARCHAR(30) not null
)

IF EXISTS(SELECT * FROM SYS.objects WHERE NAME='Sinhvien')
	DROP TABLE Sinhvien
CREATE TABLE Sinhvien
(
	MaSV CHAR(6) NOT NULL primary key,
	HotenSV NVARCHAR(40) ,
	Ngaysinh datetime,
	MALOP CHAR(3) 
)

ALTER TABLE Sinhvien
	ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY(MaLop) REFERENCES Lop(MaLop)

--NHẬP DỮ LIỆU BẢNG LOP
INSERT INTO LOP(MALOP,TENLOP)VALUES('1','21DTHE4')
INSERT INTO LOP(MALOP,TENLOP)VALUES('2','20THU5')
SELECT * FROM LOP
--NHẬP DỮ LIỆU BẢNG SINHVIEN
INSERT INTO Sinhvien(MaSV,HotenSV,MALOP,Ngaysinh) VALUES('792315',N'Lê Tuấn Thanh',1,'5/06/2003 11:12:20')
INSERT INTO Sinhvien(MaSV,HotenSV,MALOP,Ngaysinh) VALUES('146534',N'Phan Châu Tinh',2,'5/02/2003 11:12:20')
INSERT INTO Sinhvien(MaSV,HotenSV,MALOP,Ngaysinh) VALUES('147532',N'Nguyễn Thị Hằng',2,'11/5/2003 11:12:20')
INSERT INTO Sinhvien(MaSV,HotenSV,MALOP,Ngaysinh) VALUES('147732',N'Lê Thị Mỹ Tiên',1,'1/12/2003 11:12:20')
SELECT * FROM Sinhvien